include(GNUInstallDirs)
include(ExternalProject)

include(ProcessorCount)
ProcessorCount(EXT_PROJ_BUILD_CPU_COUNT)
MATH(EXPR EXT_PROJ_BUILD_CPU_COUNT "${EXT_PROJ_BUILD_CPU_COUNT}-2")

set(EXT_PROJ_SOURCES_DIR "${CMAKE_CURRENT_LIST_DIR}/sources")

set(EXT_PROJ_DIR "${CMAKE_BINARY_DIR}/external-projects")
set(EXT_PROJ_INSTALL_DIR "${EXT_PROJ_DIR}/installed")
set(EXT_PROJ_INCLUDE_DIR "${EXT_PROJ_INSTALL_DIR}/${CMAKE_INSTALL_INCLUDEDIR}")
set(EXT_PROJ_LIB_DIR "${EXT_PROJ_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}")
